### ISSUE TITLE
karma:unit TypeError at grunt-karma.js:132:20

### ISSUE THREAD

**Issue by brobrts** [karma-runner/grunt-karma#162]
Hi,

When running $grunt test -v --stack I get the following errors:
```
//***************************************************************************************
 ...
Verifying property karma.unit exists in config...OK
File: [no files]
Options: background=false, client={}
Warning: undefined is not a function Use --force to continue.
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/williamroberts/Devel/AngularJSProjects/myBassPage2/node_modules/grunt-karma/tasks/grunt-karma.js:132:20)
    at Object.<anonymous> (/Users/williamroberts/Devel/AngularJSProjects/myBassPage2/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/Users/williamroberts/Devel/AngularJSProjects/myBassPage2/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/Users/williamroberts/Devel/AngularJSProjects/myBassPage2/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/Users/williamroberts/Devel/AngularJSProjects/myBassPage2/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/Users/williamroberts/Devel/AngularJSProjects/myBassPage2/node_modules/grunt/lib/util/task.js:300:12)
    at /Users/williamroberts/Devel/AngularJSProjects/myBassPage2/node_modules/grunt/lib/util/task.js:227:11
    at process._tickCallback (node.js:355:11)

//**************************************************************************
```
I've removed all of my unit test except one very simple one to try and make sure the error isn't 
originating in my code.  From some similar but different post on line, I suspect this might have some
thing to do with version incompatibilities.  Here is my package.json:
```
//**************************************************************************
{
  "name": "mybasspage2",
  "version": "0.0.0",
  "dependencies": {},
  "repository": {},
  "devDependencies": {
    "chalk": "^0.4.0",
    "grunt": "^0.4.5",
    "grunt-autoprefixer": "^2.0.0",
    "grunt-concurrent": "^1.0.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-connect": "^0.9.0",
    "grunt-contrib-copy": "^0.7.0",
    "grunt-contrib-cssmin": "^0.12.0",
    "grunt-contrib-htmlmin": "^0.4.0",
    "grunt-contrib-imagemin": "^0.9.2",
    "grunt-contrib-jshint": "^0.11.0",
    "grunt-contrib-uglify": "^0.7.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-filerev": "^2.1.2",
    "grunt-google-cdn": "^0.4.3",
    "grunt-karma": "*",
    "grunt-newer": "^1.1.0",
    "grunt-ng-annotate": "^0.9.2",
    "grunt-svgmin": "^2.0.0",
    "grunt-usemin": "^3.0.0",
    "grunt-wiredep": "^2.0.0",
    "jshint-stylish": "^1.0.0",
    "karma-jasmine": "*",
    "karma-phantomjs-launcher": "*",
    "load-grunt-tasks": "^3.1.0",
    "time-grunt": "^1.0.0"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "test": "grunt test"
  }
}
//*************************************************************
```
Last, I've added this to my gruntfile (playlist... ).  I did see that there was an issue with globbing at one point.  That said, it fails the same when I comment these out.  
```
 copy: {
      dist: {
        files: [{
          expand: true,
          dot: true,
          cwd: '<%= yeoman.app %>',
          dest: '<%= yeoman.dist %>',
          src: [
            '*.{ico,png,txt}',
            '.htaccess',
            '*.html',
            'views/{,*/}*.html',
            'playlist-source/*.html',
            'images/{,*/}*.{webp}',
            'styles/fonts/{,*/}*.*',
            'playlist-source/audio/*.mp3',
            'playlist-source/audio/*.ogg',
            'playlist-source/data/*.json',
            'data/*.json'
          ]
        }, {
//...

filerev: {
      dist: {
        src: [
          '<%= yeoman.dist %>/scripts/{,*/}*.js',
          '<%= yeoman.dist %>/playlist-source/*.js',
          '<%= yeoman.dist %>/styles/{,*/}*.css',
          '<%= yeoman.dist %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
          '<%= yeoman.dist %>/styles/fonts/*'
        ]
      }
    },
//*****************************************************
```
Thanks,
Billy

**Comment by Dignifiedquire** [comment]
It sounds like you are using an outdated version of `karma`. Try updating `grunt-karma` and `karma` to the latest versions.

**Comment by brobrts** [comment]
Big thanks!!  I was using karma 0.12.35.  Everything is working now.  

I'm new to this and need to learn npm, yo, grunt, bower,karma... a bit better.  It seems upgrades happen as a side effect of running certian commands in the environment - which leaves version conflicts that you only discover when things stop running.  Is this true?  I still haven't discovered the action I took to break things.

**Comment by brobrts** [comment]
Thanks Friedel!!  upgraded from karma 0.12.35 (and grunt-karma) and fixed
it.
