### ISSUE TITLE
Error when installing npm -g karma

### ISSUE THREAD

**Issue by sylfree9999** [karma-runner/grunt-karma#169]
Hi all,

I got the error installing the npm karma. Here is a snap shot of the error log:

16040 silly lifecycle bufferutil@1.2.1~preinstall: no script for preinstall, continuing
16041 info linkStuff bufferutil@1.2.1
16042 silly linkStuff bufferutil@1.2.1 has C:\Program Files\nodejs\node_modules\karma\node_modules as its parent node_modules
16043 verbose linkBins bufferutil@1.2.1
16044 verbose linkMans bufferutil@1.2.1
16045 verbose rebuildBundles bufferutil@1.2.1
16046 info lifecycle bufferutil@1.2.1~install: bufferutil@1.2.1
16047 verbose lifecycle bufferutil@1.2.1~install: unsafe-perm in lifecycle true
16048 verbose lifecycle bufferutil@1.2.1~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\karma\node_modules\bufferutil\node_modules\.bin;C:\Program Files\nodejs\node_modules\karma\node_modules\.bin;C:\Program Files\nodejs\node_modules\.bin;C:\python3.5\Scripts\;C:\python3.5\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Spencer.Shao\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Java\jdk1.8.0_60\bin;C:\Program Files\Java\jdk1.8.0_60\jre\bin;E:/apache-ant-1.9.6/bin;C:\Program Files\nodejs\;E:\Git\cmd;E:\android-sdk\platform-tools;E:\android-sdk\tools;C:\Users\Spencer.Shao\AppData\Local\Programs\Python\Python35-32;C:\Users\Spencer.Shao\AppData\Roaming\npm
16049 verbose lifecycle bufferutil@1.2.1~install: CWD: C:\Program Files\nodejs\node_modules\karma\node_modules\bufferutil
16050 silly lifecycle bufferutil@1.2.1~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
16051 silly lifecycle bufferutil@1.2.1~install: Returned: code: 1  signal: null
16052 info lifecycle bufferutil@1.2.1~install: Failed to exec install script
16053 verbose unlock done using C:\Users\Spencer.Shao\AppData\Roaming\npm-cache\_locks\staging-dfd8fbf9c1feea0f.lock for C:\Program Files\nodejs\node_modules\.staging
16054 silly rollbackFailedOptional Starting
16055 silly rollbackFailedOptional Finishing
16056 silly runTopLevelLifecycles Starting
16057 silly runTopLevelLifecycles Finishing
16058 silly install printInstalled
16059 verbose stack Error: bufferutil@1.2.1 install: `node-gyp rebuild`
16059 verbose stack Exit status 1
16059 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:233:16)
16059 verbose stack     at emitTwo (events.js:87:13)
16059 verbose stack     at EventEmitter.emit (events.js:172:7)
16059 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
16059 verbose stack     at emitTwo (events.js:87:13)
16059 verbose stack     at ChildProcess.emit (events.js:172:7)
16059 verbose stack     at maybeClose (internal/child_process.js:818:16)
16059 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
16060 verbose pkgid bufferutil@1.2.1
16061 verbose cwd C:\
16062 error Windows_NT 10.0.10240
16063 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
16064 error node v4.1.2
16065 error npm  v3.3.6
16066 error code ELIFECYCLE
16067 error bufferutil@1.2.1 install: `node-gyp rebuild`
16067 error Exit status 1
16068 error Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
16068 error This is most likely a problem with the bufferutil package,
16068 error not with npm itself.
16068 error Tell the author that this fails on your system:
16068 error     node-gyp rebuild
16068 error You can get their info via:
16068 error     npm owner ls bufferutil
16068 error There is likely additional logging output above.
16069 verbose exit [ 1, true ]

![npm_error](https://cloud.githubusercontent.com/assets/15099465/10732700/3c8b3456-7c36-11e5-9e49-5a8667c80633.png)

I have tried to open the directory as said above, but I did not find the karma folder under the nodejs-->node_modules.
Any idea why this happens?

**Comment by sylfree9999** [comment]
After several trials, I found out that this is because I did not install VC++ tools when installing visual studio 2015. Just install the files below, then all is working out.
![vs_install vc](https://cloud.githubusercontent.com/assets/15099465/10747794/71597356-7c94-11e5-93d7-0b88edf886db.png)
