### ISSUE TITLE
Task "karma:unit" not found. Use --force to continue

### ISSUE THREAD

**Issue by YunYangAccela** [karma-runner/grunt-karma#212]
Loading "grunt-karma.js" tasks...?[31mERROR?[39m
     [exec] ?[31m>> ?[39mTypeError: Cannot read property 'prototype' of undefined
     [exec] ?[33mWarning: Task "karma:unit" not found. Use --force to continue.?[39m

**Comment by JohnRiv** [comment]
I got this same error on a project that used to work but I hadn't touched in awhile. Went back and noticed when I ran `npm install` this message was output at the end:

```
npm WARN karma-jasmine@1.1.0 requires a peer of jasmine-core@* but none was installed.
```

Most likely because I've updated Node.js (and therefore NPM) since I last touched the project.

Fix was to install `jasmine-core`

```
$ npm install jasmine-core --save-dev
```

**Comment by tiaoshi** [comment]
After upgrading to node.js 7.5.0, I encountered this error too:

```
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
```

**Comment by tiaoshi** [comment]
This error is due to one dependency of karma, socket.io: https://github.com/socketio/socket.io/pull/2790

**Comment by indriesergiu** [comment]
I've turned on verbose (-v) mode and found the following stacktrace

Registering "grunt-karma" local Npm module tasks.
Reading /Users/sergiu/code/rooms-admin-portal/node_modules/grunt-karma/package.json...OK
Parsing /Users/sergiu/code/rooms-admin-portal/node_modules/grunt-karma/package.json...OK
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
>>     at Object.<anonymous> (/Users/sergiu/code/rooms-admin-portal/node_modules/karma/node_modules/socket.io/lib/store.js:35:41)
>>     at Module._compile (module.js:571:32)
>>     at Object.Module._extensions..js (module.js:580:10)
>>     at Module.load (module.js:488:32)
>>     at tryModuleLoad (module.js:447:12)
>>     at Function.Module._load (module.js:439:3)
>>     at Module.require (module.js:498:17)
>>     at require (internal/module.js:20:19)
>>     at Object.<anonymous> (/Users/sergiu/code/rooms-admin-portal/node_modules/karma/node_modules/socket.io/lib/manager.js:16:13)
>>     at Module._compile (module.js:571:32)

I've tried reinstalling socket.io but it didn't help.

Any ideas?

**Comment by indriesergiu** [comment]
Fixed by upgrading to
"grunt-karma": "^0.12.2",
"karma": "^1.6.0",

**Comment by bargitta** [comment]
Tests fails to run on Node 9.3.0

**Comment by maazmmd** [comment]
@indriesergiu .. Thanks .. Just making changes to karma and grunt karma helped me..

**Comment by snimavat** [comment]
Getting the same problem with socketio
grunt-cli v1.3.2
grunt v1.0.4
Karma version: 4.0.0
grunt-karma@3.0.2
